const Map<String, dynamic> tileConfigurationJson = <String, dynamic>{
  'tiles': <Map<String, dynamic>>[
    {
      'sectionId': 'applicant_kyc',
      'title': 'Applicant KYC',
      'cards': [
        {
          'cardId': 'identity',
          'title': 'Identity Details',
          'fields': [
            {
              'fieldId': 'applicant_name',
              'label': 'Applicant Name',
              'type': 'TEXT',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'validation': {'minLength': 3},
              'scenarioOverrides': {
                'DEALER_FLOW': {'mandatory': false},
                'POST_SANCTION_REVIEW': {'editable': false},
              },
            },
            {
              'fieldId': 'pan_number',
              'label': 'PAN Number',
              'type': 'TEXT',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'validation': {
                'regex': r'^[A-Z]{5}[0-9]{4}[A-Z]$',
                'message': 'Invalid PAN format',
              },
            },
            {
              'fieldId': 'aadhaar_number',
              'label': 'Aadhaar Number',
              'type': 'NUMBER',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'validation': {'minLength': 12, 'maxLength': 12},
              'scenarioOverrides': {
                'DEALER_FLOW': {'visible': false, 'mandatory': false},
              },
            },
            {
              'fieldId': 'kyc_verified',
              'label': 'KYC Verified',
              'type': 'DROPDOWN',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'options': ['Yes', 'No'],
              'scenarioOverrides': {
                'POST_SANCTION_REVIEW': {'editable': false},
              },
            },
            {
              'fieldId': 'kyc_remarks',
              'label': 'KYC Remarks',
              'type': 'TEXT',
              'mandatory': false,
              'editable': true,
              'editableWhen': {
                'fieldId': 'kyc_verified',
                'operator': 'equals',
                'value': 'No',
              },
              'mandatoryWhen': {
                'fieldId': 'kyc_verified',
                'operator': 'equals',
                'value': 'No',
              },
              'visible': true,
              'visibleWhen': {
                'fieldId': 'kyc_verified',
                'operator': 'equals',
                'value': 'No',
              },
              'scenarioOverrides': {
                'POST_SANCTION_REVIEW': {
                  'visible': true,
                  'mandatory': true,
                  'editable': true,
                },
              },
            },
          ],
        },
      ],
    },
    {
      'sectionId': 'collateral_details',
      'title': 'Collateral Details',
      'cards': [
        {
          'cardId': 'asset',
          'title': 'Asset & Vehicle',
          'fields': [
            {
              'fieldId': 'vehicle_type',
              'label': 'Vehicle Type',
              'type': 'DROPDOWN',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'options': ['Truck', 'Tipper', 'LCV'],
            },
            {
              'fieldId': 'vehicle_cost',
              'label': 'Vehicle Cost',
              'type': 'NUMBER',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'validation': {'min': 100000},
              'scenarioOverrides': {
                'USED_VEHICLE': {
                  'validation': {'min': 50000, 'max': 5000000},
                },
              },
            },
            {
              'fieldId': 'margin_percent',
              'label': 'Margin %',
              'type': 'NUMBER',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'validation': {'min': 5, 'max': 50},
              'scenarioOverrides': {
                'USED_VEHICLE': {
                  'mandatory': true,
                  'validation': {'min': 10, 'max': 60},
                },
              },
            },
            {
              'fieldId': 'loan_eligible',
              'label': 'Loan Eligible Amount',
              'type': 'NUMBER',
              'mandatory': false,
              'editable': false,
              'visible': true,
              'calculation': {
                'operation': 'subtract',
                'sources': ['vehicle_cost', 'margin_percent'],
                'precision': 2,
              },
            },
          ],
        },
      ],
    },
    {
      'sectionId': 'viability_credit',
      'title': 'Viability & Credit',
      'cards': [
        {
          'cardId': 'income',
          'title': 'Income Analysis',
          'fields': [
            {
              'fieldId': 'monthly_income',
              'label': 'Monthly Income',
              'type': 'NUMBER',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'validation': {'min': 0},
            },
            {
              'fieldId': 'existing_emi',
              'label': 'Existing EMI',
              'type': 'NUMBER',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'validation': {'min': 0},
            },
            {
              'fieldId': 'foir_percent',
              'label': 'FOIR %',
              'type': 'NUMBER',
              'mandatory': false,
              'editable': false,
              'visible': true,
              'calculation': {
                'operation': 'percent',
                'sources': ['existing_emi', 'monthly_income'],
                'precision': 2,
              },
            },
            {
              'fieldId': 'credit_score',
              'label': 'Credit Score',
              'type': 'NUMBER',
              'mandatory': false,
              'editable': true,
              'visible': true,
              'validation': {'min': 300, 'max': 900},
            },
            {
              'fieldId': 'risk_band',
              'label': 'Risk Band',
              'type': 'DROPDOWN',
              'mandatory': false,
              'editable': true,
              'visible': true,
              'options': ['Low', 'Medium', 'High'],
              'mandatoryWhen': {
                'fieldId': 'credit_score',
                'operator': 'notEmpty',
                'value': null,
              },
              'scenarioOverrides': {
                'HIGH_RISK_REVIEW': {'mandatory': true},
              },
            },
          ],
        },
      ],
    },
    {
      'sectionId': 'loan_terms',
      'title': 'Loan Terms, Charges & Payout',
      'cards': [
        {
          'cardId': 'terms',
          'title': 'Loan Terms',
          'fields': [
            {
              'fieldId': 'loan_amount',
              'label': 'Loan Amount',
              'type': 'NUMBER',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'validation': {'min': 100000},
            },
            {
              'fieldId': 'tenure_months',
              'label': 'Tenure (Months)',
              'type': 'NUMBER',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'validation': {'min': 12, 'max': 84},
            },
            {
              'fieldId': 'interest_rate',
              'label': 'Interest Rate %',
              'type': 'NUMBER',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'validation': {'min': 5, 'max': 28},
            },
            {
              'fieldId': 'processing_fee',
              'label': 'Processing Fee',
              'type': 'NUMBER',
              'mandatory': false,
              'editable': true,
              'visible': true,
            },
            {
              'fieldId': 'net_disbursal',
              'label': 'Net Disbursal',
              'type': 'NUMBER',
              'mandatory': false,
              'editable': false,
              'visible': true,
              'calculation': {
                'operation': 'subtract',
                'sources': ['loan_amount', 'processing_fee'],
                'precision': 2,
              },
            },
          ],
        },
      ],
    },
    {
      'sectionId': 'co_applicant',
      'title': 'Co-Applicant',
      'cards': [
        {
          'cardId': 'co_profile',
          'title': 'Co-Applicant Profile',
          'fields': [
            {
              'fieldId': 'has_coapplicant',
              'label': 'Has Co-Applicant?',
              'type': 'DROPDOWN',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'options': ['Yes', 'No'],
            },
            {
              'fieldId': 'coapplicant_name',
              'label': 'Co-Applicant Name',
              'type': 'TEXT',
              'mandatory': false,
              'editable': true,
              'visible': true,
              'visibleWhen': {
                'fieldId': 'has_coapplicant',
                'operator': 'equals',
                'value': 'Yes',
              },
              'mandatoryWhen': {
                'fieldId': 'has_coapplicant',
                'operator': 'equals',
                'value': 'Yes',
              },
            },
            {
              'fieldId': 'coapplicant_relationship',
              'label': 'Relationship',
              'type': 'DROPDOWN',
              'mandatory': false,
              'editable': true,
              'visible': true,
              'options': ['Spouse', 'Brother', 'Sister', 'Parent', 'Other'],
              'visibleWhen': {
                'fieldId': 'has_coapplicant',
                'operator': 'equals',
                'value': 'Yes',
              },
            },
          ],
        },
      ],
    },
    {
      'sectionId': 'guarantor',
      'title': 'Guarantor',
      'cards': [
        {
          'cardId': 'guarantor_details',
          'title': 'Guarantor Details',
          'fields': [
            {
              'fieldId': 'has_guarantor',
              'label': 'Has Guarantor?',
              'type': 'DROPDOWN',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'options': ['Yes', 'No'],
            },
            {
              'fieldId': 'guarantor_name',
              'label': 'Guarantor Name',
              'type': 'TEXT',
              'mandatory': false,
              'editable': true,
              'visible': true,
              'visibleWhen': {
                'fieldId': 'has_guarantor',
                'operator': 'equals',
                'value': 'Yes',
              },
              'mandatoryWhen': {
                'fieldId': 'has_guarantor',
                'operator': 'equals',
                'value': 'Yes',
              },
            },
            {
              'fieldId': 'guarantor_pan',
              'label': 'Guarantor PAN',
              'type': 'TEXT',
              'mandatory': false,
              'editable': true,
              'visible': true,
              'visibleWhen': {
                'fieldId': 'has_guarantor',
                'operator': 'equals',
                'value': 'Yes',
              },
              'validation': {
                'regex': r'^[A-Z]{5}[0-9]{4}[A-Z]$',
                'message': 'Invalid PAN format',
              },
            },
          ],
        },
      ],
    },
    {
      'sectionId': 'additional_info',
      'title': 'Additional Info',
      'cards': [
        {
          'cardId': 'business_meta',
          'title': 'Business Meta',
          'fields': [
            {
              'fieldId': 'business_vintage',
              'label': 'Business Vintage (Years)',
              'type': 'NUMBER',
              'mandatory': false,
              'editable': true,
              'visible': true,
            },
            {
              'fieldId': 'gst_available',
              'label': 'GST Available',
              'type': 'DROPDOWN',
              'mandatory': false,
              'editable': true,
              'visible': true,
              'options': ['Yes', 'No'],
            },
            {
              'fieldId': 'gst_number',
              'label': 'GST Number',
              'type': 'TEXT',
              'mandatory': false,
              'editable': true,
              'visible': true,
              'visibleWhen': {
                'fieldId': 'gst_available',
                'operator': 'equals',
                'value': 'Yes',
              },
              'mandatoryWhen': {
                'fieldId': 'gst_available',
                'operator': 'equals',
                'value': 'Yes',
              },
            },
          ],
        },
      ],
    },
    {
      'sectionId': 'premises_verification',
      'title': 'Premises Verification',
      'cards': [
        {
          'cardId': 'pv_details',
          'title': 'Verification Details',
          'fields': [
            {
              'fieldId': 'premises_type',
              'label': 'Premises Type',
              'type': 'DROPDOWN',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'options': ['Owned', 'Rented', 'Leased'],
            },
            {
              'fieldId': 'verified_on',
              'label': 'Verified On',
              'type': 'DATE',
              'mandatory': false,
              'editable': true,
              'visible': true,
            },
            {
              'fieldId': 'premises_score',
              'label': 'Premises Score',
              'type': 'NUMBER',
              'mandatory': false,
              'editable': false,
              'visible': true,
              'calculation': {
                'operation': 'sum',
                'sources': ['business_vintage'],
                'precision': 0,
              },
            },
          ],
        },
      ],
    },
    {
      'sectionId': 'banking_payments',
      'title': 'Banking & Payments',
      'cards': [
        {
          'cardId': 'banking',
          'title': 'Banking Summary',
          'fields': [
            {
              'fieldId': 'bank_name',
              'label': 'Primary Bank',
              'type': 'TEXT',
              'mandatory': true,
              'editable': true,
              'visible': true,
            },
            {
              'fieldId': 'avg_balance',
              'label': 'Average Balance',
              'type': 'NUMBER',
              'mandatory': false,
              'editable': true,
              'visible': true,
            },
            {
              'fieldId': 'emi_mode',
              'label': 'EMI Mode',
              'type': 'DROPDOWN',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'options': ['NACH', 'ECS', 'Cash'],
            },
          ],
        },
      ],
    },
    {
      'sectionId': 'document_upload',
      'title': 'Document Upload',
      'cards': [
        {
          'cardId': 'docs',
          'title': 'Documents',
          'fields': [
            {
              'fieldId': 'kyc_uploaded',
              'label': 'KYC Uploaded',
              'type': 'DROPDOWN',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'options': ['Yes', 'No'],
            },
            {
              'fieldId': 'bank_statement_uploaded',
              'label': 'Bank Statement Uploaded',
              'type': 'DROPDOWN',
              'mandatory': false,
              'editable': true,
              'visible': true,
              'options': ['Yes', 'No'],
            },
            {
              'fieldId': 'upload_remarks',
              'label': 'Upload Remarks',
              'type': 'TEXT',
              'mandatory': false,
              'editable': true,
              'visible': true,
              'visibleWhen': {
                'fieldId': 'bank_statement_uploaded',
                'operator': 'equals',
                'value': 'No',
              },
            },
          ],
        },
      ],
    },
    {
      'sectionId': 're_cse_note',
      'title': 'RE / CSE Note',
      'cards': [
        {
          'cardId': 'notes',
          'title': 'Final Notes',
          'fields': [
            {
              'fieldId': 're_note',
              'label': 'RE Note',
              'type': 'TEXT',
              'mandatory': false,
              'editable': true,
              'visible': true,
            },
            {
              'fieldId': 'cse_note',
              'label': 'CSE Note',
              'type': 'TEXT',
              'mandatory': false,
              'editable': true,
              'visible': true,
            },
            {
              'fieldId': 'final_decision',
              'label': 'Final Decision',
              'type': 'DROPDOWN',
              'mandatory': true,
              'editable': true,
              'visible': true,
              'options': ['Approve', 'Refer', 'Reject'],
            },
          ],
        },
      ],
    },
  ],
};
